apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app:  mysql-job-s
  name:  mysql-job-s
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  mysql-job-s
  template:
    metadata:
      labels:
        app:  mysql-job-s
    spec:
      containers:
        - env:
            - name: PGDATA
              value: /data/postgres
            - name: POSTGRES_DB
              value: inventory-service
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: ptechie
          image: postgres
          name:  mysql-job-s
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /data/postgres
              name:  mysql-job-s-claim0
      restartPolicy: Always
      volumes:
        - name:  mysql-job-s-claim0
          persistentVolumeClaim:
            claimName:  mysql-job-s-claim0

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app:  mysql-job-s
  name:  mysql-job-s
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app:  mysql-job-s
status:
  loadBalancer: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app:  mysql-job-s-claim0
  name:  mysql-job-s-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
